CREATE TABLE IF NOT EXISTS models (
    id SERIAL PRIMARY KEY,
    title VARCHAR(64) NOT NULL UNIQUE
);

INSERT INTO models (title)
VALUES
    ('Nissan Almera'),
    ('Volkswagen Polo'),
    ('Ravon R2'),
    ('Kia Picanto'),
    ('Nissan Rogue'),
    ('Geely Coolray'),
    ('Hyundai Creta'),
    ('Chery Tiggo 4 PRO'),
    ('Haval F7'),
    ('Hyundai Elantra'),
    ('Geely Emgrand'),
    ('Skoda Octavia'),
    ('OMODA S5'),
    ('Chevrolet Monza'),
    ('Kia Ceed'),
    ('Mitsubishi Asx'),
    ('Kia Rio New'),
    ('Hyundai Solaris New'),
    ('Toyota Corolla'),
    ('Kia Rio'),
    ('Skoda Rapid'),
    ('Hyundai Solaris'),
    ('Volkswagen Jetta'),
    ('Nissan Tiida'),
    ('BMW X5 XDRIVE 40D'),
    ('Voyah Free'),
    ('BMW 530D XDRIVE'),
    ('BMW X5 XDRIVE 30D'),
    ('BMW 520D XDRIVE'),
    ('Geely Monjaro'),
    ('Jetour T2'),
    ('Toyota RAV4'),
    ('Genesis G70'),
    ('Mercedes-Benz С180'),
    ('BMW 320D XDRIVE'),
    ('Chery Tiggo 7 PRO MAX'),
    ('Lexus GS350'),
    ('Toyota Camry'),
    ('Changan UNI-V'),
    ('KIA JF Optima'),
    ('Volkswagen Passat'),
    ('Ford Mondeo'),
    ('Tesla Model Y'),
    ('Tesla Model X'),
    ('Tesla Model 3');